### ISSUE TITLE
Naming inconsistency in the new relIso variable

### ISSUE THREAD

**Issue by kskovpen** [GhentAnalysis/heavyNeutrino#105]
This inconsistency does not seem to affect the storage of _relIsoDeltaBeta, but probably it would be better to call it the same name in the definition of the TTree branch (i.e. _relIsoDeltaBeta vs _relIsoDeltaBetaB):

https://github.com/GhentAnalysis/heavyNeutrino/blob/master/multilep/src/LeptonAnalyzer.cc#L88

**Comment by tomcornelis** [comment]
done
