### ISSUE TITLE
UL:  Fix all psWeights

### ISSUE THREAD

**Issue by lwezenbe** [GhentAnalysis/heavyNeutrino#139]
**From submission checklist**

there are now 46 psWeights available (index 0 through 45) (currently storing 14). The ordering has changed so that we need indices 4,5, 26, and 27 --> we're currently not storing the last 2. In principle the order depends on the pythia8 version, so we need to be sure it's consistent for all UL samples.

**Comment by gmestdac** [comment]
How many psWeights are available + their naming and order is saved in the gen lumi info header
you can print this “ GenLumiInfoHeader”, following instructions here: 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HowToPDF 

maxNumberOfPsWeights needs to be increased, making it too large doesn't seem to be a problem if I understand this line correctly:
https://github.com/GhentAnalysis/heavyNeutrino/blob/UL_master/multilep/src/LheAnalyzer.cc#L113
It should just save however many are available if maxNumberOfPsWeights is higher than that

Checking if this new ordering is the same in all UL samples, and if not picking the right ones for each sample is annoying but is not something to worry about in the heavyNeutrino code (unless someone knows how to determine the ordering ourselves at this level)
