### ISSUE TITLE
UL: Issue in jetPileupId

### ISSUE THREAD

**Issue by lwezenbe** [GhentAnalysis/heavyNeutrino#141]
David is seeing strange values for the jetPileupId, this needs to be investigated

**Comment by knollejo** [comment]
This ID has been added in this commit: 623edd36d2576ebfe49a9e08a9069b13a5fd1713

The values of the variables are assigned like this:

        if( jet.hasUserFloat("pileupJetId:fullDiscriminant") ) _jetPileupIdFullDisc[_nJets] = jet.userFloat("pileupJetId:fullDiscriminant");
        if( jet.hasUserInt("pileupJetIdUpdated:fullId") ) _jetPileupIdFullId[_nJets] = jet.userInt("pileupJetIdUpdated:fullId");

The first line uses "pileupJetId", and the second line uses "pileupJetIdUpdated". This is already inconsistent. I think that "pileupJetId" should work out-of-the-box without the additional task added in the jetsequence in that commit. Also, the [twiki](https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetIDUL) mentions that the new task should be added to the path, which we don't do, so maybe that is the cause of the problem (although I would expect a runtime error in that case). Anyway, David and I will investigate further.

**Comment by knollejo** [comment]
The problems in David's tuples seemed to have been a singular issue from corrupted ntuple production, and the values appear to be fine after rerunning the ntuples.

For the inconsistency, I included the commit 44fd87aa9c324e430df1d7e615f856e68d3155e1 in a pull request that switches to `pileupJetIdUpdated` for both values. This slightly changes the value of `fullDiscriminant` in three of the four years (see c9074316bfbcb8e285ef039266122f1eba1c6a96), so it seems that the recalculation indeed has an effect.
